package auth

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"sync"
	"time"

	"github.com/emersion/go-sasl"
	"golang.org/x/oauth2"
	"golang.org/x/oauth2/google"
)

const gmailIMAPScope = "https://mail.google.com/"

// stateExpiry is how long a pending OAuth state remains valid.
const stateExpiry = 10 * time.Minute

// GmailProvider implements Provider for Google accounts using OAuth2.
type GmailProvider struct {
	config     *oauth2.Config
	tokenStore TokenStore

	mu            sync.Mutex
	pendingStates map[string]time.Time // state -> expiry

	// accountLocks serializes token load-refresh-save per account.
	accountLocks map[string]*sync.Mutex
}

// NewGmailProvider creates a new Gmail auth provider.
func NewGmailProvider(clientID, clientSecret, redirectURL string, tokenStore TokenStore) *GmailProvider {
	return &GmailProvider{
		config: &oauth2.Config{
			ClientID:     clientID,
			ClientSecret: clientSecret,
			RedirectURL:  redirectURL,
			Scopes:       []string{gmailIMAPScope},
			Endpoint:     google.Endpoint,
		},
		tokenStore:    tokenStore,
		pendingStates: make(map[string]time.Time),
		accountLocks:  make(map[string]*sync.Mutex),
	}
}

// Name returns the provider identifier.
func (g *GmailProvider) Name() string {
	return "gmail"
}

// accountLock returns (or creates) a per-account mutex.
func (g *GmailProvider) accountLock(accountID string) *sync.Mutex {
	g.mu.Lock()
	defer g.mu.Unlock()
	m, ok := g.accountLocks[accountID]
	if !ok {
		m = &sync.Mutex{}
		g.accountLocks[accountID] = m
	}
	return m
}

// StartFlow generates an authorization URL the user must visit.
func (g *GmailProvider) StartFlow() (string, error) {
	state, err := randomState()
	if err != nil {
		return "", fmt.Errorf("generating state: %w", err)
	}

	g.mu.Lock()
	g.pendingStates[state] = time.Now().Add(stateExpiry)
	g.mu.Unlock()

	url := g.config.AuthCodeURL(state, oauth2.AccessTypeOffline, oauth2.SetAuthURLParam("prompt", "consent"))
	return url, nil
}

// CompleteFlowWithAccount exchanges the auth code and saves the token
// under the given account ID. The state parameter is validated against
// pending states generated by StartFlow.
func (g *GmailProvider) CompleteFlowWithAccount(ctx context.Context, state, code, accountID string) error {
	// Validate and consume the state atomically.
	g.mu.Lock()
	expiry, ok := g.pendingStates[state]
	if ok {
		delete(g.pendingStates, state) // consume to prevent reuse
	}
	g.mu.Unlock()

	if !ok {
		return fmt.Errorf("unknown or already-used OAuth state")
	}
	if time.Now().After(expiry) {
		return fmt.Errorf("OAuth state expired")
	}

	token, err := g.config.Exchange(ctx, code)
	if err != nil {
		return fmt.Errorf("exchanging code: %w", err)
	}

	if err := g.tokenStore.Save(ctx, accountID, token); err != nil {
		return fmt.Errorf("saving token: %w", err)
	}

	return nil
}

// SASLClient returns an XOAUTH2 SASL client for IMAP auth.
// It loads the stored token for the account, refreshes it if needed,
// and returns a ready-to-use SASL client.
// The email parameter is used as the SASL identity (not the internal accountID).
func (g *GmailProvider) SASLClient(ctx context.Context, accountID, email string) (sasl.Client, error) {
	// Serialize token load-refresh-save per account to prevent race conditions.
	lock := g.accountLock(accountID)
	lock.Lock()
	defer lock.Unlock()

	token, err := g.tokenStore.Load(ctx, accountID)
	if err != nil {
		return nil, fmt.Errorf("loading token: %w", err)
	}

	// Create a token source that auto-refreshes
	ts := g.config.TokenSource(ctx, token)
	freshToken, err := ts.Token()
	if err != nil {
		return nil, fmt.Errorf("refreshing token: %w", err)
	}

	// Persist the refreshed token if it changed
	if freshToken.AccessToken != token.AccessToken {
		if err := g.tokenStore.Save(ctx, accountID, freshToken); err != nil {
			return nil, fmt.Errorf("saving refreshed token: %w", err)
		}
	}

	return &xoauth2Client{
		username: email,
		token:    freshToken.AccessToken,
	}, nil
}

// xoauth2Client implements sasl.Client for the XOAUTH2 mechanism
// used by Gmail IMAP. The auth string format is:
// "user=" + user + "\x01" + "auth=Bearer " + token + "\x01\x01"
type xoauth2Client struct {
	username string
	token    string
}

func (c *xoauth2Client) Start() (string, []byte, error) {
	resp := fmt.Sprintf("user=%s\x01auth=Bearer %s\x01\x01", c.username, c.token)
	return "XOAUTH2", []byte(resp), nil
}

func (c *xoauth2Client) Next(challenge []byte) ([]byte, error) {
	// XOAUTH2 doesn't have additional challenges in the success case.
	// If we get a challenge, it's an error response from the server.
	return nil, fmt.Errorf("XOAUTH2 challenge: %s", string(challenge))
}

func randomState() (string, error) {
	b := make([]byte, 16)
	if _, err := rand.Read(b); err != nil {
		return "", err
	}
	return hex.EncodeToString(b), nil
}
